// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract BackBank2 {
    constructor() {}

    function getGingham() external pure returns (string memory) {
        return "<svg viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><g id=\"bg\"><rect width=\"24\" height=\"24\" fill=\"#FFF0F5\"/><rect width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"4\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"8\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"12\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"16\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"20\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"4\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"8\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"12\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"16\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"20\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/></g></svg>";
    }
    function getHoundstooth() external pure returns (string memory) {
        return "<svg width=\"384\" height=\"384\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\" shape-rendering=\"crispEdges\"><defs><pattern id=\"h\" width=\"8\" height=\"8\" patternUnits=\"userSpaceOnUse\"><rect width=\"3\" height=\"1\" fill=\"#dda0df\"/><rect y=\"1\" width=\"2\" height=\"1\" fill=\"#dda0df\"/><rect y=\"2\" width=\"1\" height=\"1\" fill=\"#dda0df\"/><rect x=\"4\" y=\"4\" width=\"3\" height=\"1\" fill=\"#dda0df\"/><rect x=\"4\" y=\"5\" width=\"2\" height=\"1\" fill=\"#dda0df\"/><rect x=\"4\" y=\"6\" width=\"1\" height=\"1\" fill=\"#dda0df\"/><rect x=\"3\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"2\" y=\"1\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"1\" y=\"2\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect y=\"3\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"7\" y=\"4\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"6\" y=\"5\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"5\" y=\"6\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"4\" y=\"7\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"4\" width=\"4\" height=\"4\" fill=\"#e6e8fc\"/><rect y=\"4\" width=\"4\" height=\"4\" fill=\"#e6e8fc\"/><rect x=\"3\" y=\"1\" width=\"1\" height=\"3\" fill=\"#FFF\"/><rect x=\"2\" y=\"2\" width=\"1\" height=\"2\" fill=\"#FFF\"/><rect x=\"1\" y=\"3\" width=\"1\" height=\"1\" fill=\"#FFF\"/><rect x=\"7\" y=\"5\" width=\"1\" height=\"3\" fill=\"#FFF\"/><rect x=\"6\" y=\"6\" width=\"1\" height=\"2\" fill=\"#FFF\"/><rect x=\"5\" y=\"7\" width=\"1\" height=\"1\" fill=\"#FFF\"/></pattern></defs><rect width=\"24\" height=\"24\" fill=\"url(#h)\"/></svg>";
    }
    function getPolkaDots() external pure returns (string memory) {
        return "<svg viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><g id=\"bg\"><rect width=\"24\" height=\"24\" fill=\"#E0FFFF\"/><rect x=\"1\" y=\"1\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"7\" y=\"1\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"13\" y=\"1\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"19\" y=\"1\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"4\" y=\"5\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"10\" y=\"5\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"16\" y=\"5\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"22\" y=\"5\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"1\" y=\"9\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"7\" y=\"9\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"13\" y=\"9\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"19\" y=\"9\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"4\" y=\"13\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"10\" y=\"13\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"16\" y=\"13\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"22\" y=\"13\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"1\" y=\"17\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"7\" y=\"17\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"13\" y=\"17\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"19\" y=\"17\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"4\" y=\"21\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"10\" y=\"21\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"16\" y=\"21\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"22\" y=\"21\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/></g></svg>";
    }

    function getBackSVG(uint8 backId) public pure returns (string memory) {
        if (backId == 4) return "<svg viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><g id=\"bg\"><rect width=\"24\" height=\"24\" fill=\"#FFF0F5\"/><rect width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"4\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"8\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"12\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"16\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect y=\"20\" width=\"24\" height=\"2\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"4\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"8\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"12\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"16\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/><rect x=\"20\" width=\"2\" height=\"24\" fill=\"#FFB6C1\" opacity=\"0.5\"/></g></svg>";
        if (backId == 5) return "<svg viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\" shape-rendering=\"crispEdges\"><defs><pattern id=\"h\" width=\"8\" height=\"8\" patternUnits=\"userSpaceOnUse\"><rect width=\"3\" height=\"1\" fill=\"#dda0df\"/><rect y=\"1\" width=\"2\" height=\"1\" fill=\"#dda0df\"/><rect y=\"2\" width=\"1\" height=\"1\" fill=\"#dda0df\"/><rect x=\"4\" y=\"4\" width=\"3\" height=\"1\" fill=\"#dda0df\"/><rect x=\"4\" y=\"5\" width=\"2\" height=\"1\" fill=\"#dda0df\"/><rect x=\"4\" y=\"6\" width=\"1\" height=\"1\" fill=\"#dda0df\"/><rect x=\"3\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"2\" y=\"1\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"1\" y=\"2\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect y=\"3\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"7\" y=\"4\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"6\" y=\"5\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"5\" y=\"6\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"4\" y=\"7\" width=\"1\" height=\"1\" fill=\"#f0d5f0\"/><rect x=\"4\" width=\"4\" height=\"4\" fill=\"#e6e8fc\"/><rect y=\"4\" width=\"4\" height=\"4\" fill=\"#e6e8fc\"/><rect x=\"3\" y=\"1\" width=\"1\" height=\"3\" fill=\"#FFF\"/><rect x=\"2\" y=\"2\" width=\"1\" height=\"2\" fill=\"#FFF\"/><rect x=\"1\" y=\"3\" width=\"1\" height=\"1\" fill=\"#FFF\"/><rect x=\"7\" y=\"5\" width=\"1\" height=\"3\" fill=\"#FFF\"/><rect x=\"6\" y=\"6\" width=\"1\" height=\"2\" fill=\"#FFF\"/><rect x=\"5\" y=\"7\" width=\"1\" height=\"1\" fill=\"#FFF\"/></pattern></defs><rect width=\"24\" height=\"24\" fill=\"url(#h)\"/></svg>";
        if (backId == 6) return "<svg viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><g id=\"bg\"><rect width=\"24\" height=\"24\" fill=\"#E0FFFF\"/><rect x=\"1\" y=\"1\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"7\" y=\"1\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"13\" y=\"1\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"19\" y=\"1\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"4\" y=\"5\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"10\" y=\"5\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"16\" y=\"5\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"22\" y=\"5\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"1\" y=\"9\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"7\" y=\"9\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"13\" y=\"9\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"19\" y=\"9\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"4\" y=\"13\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"10\" y=\"13\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"16\" y=\"13\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"22\" y=\"13\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"1\" y=\"17\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"7\" y=\"17\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"13\" y=\"17\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"19\" y=\"17\" width=\"2\" height=\"2\" fill=\"#00CED1\"/><rect x=\"4\" y=\"21\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"10\" y=\"21\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"16\" y=\"21\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/><rect x=\"22\" y=\"21\" width=\"2\" height=\"2\" fill=\"#48D1CC\"/></g></svg>";
        revert("Back ID not in this bank");
    }

    function getBackName(uint8 backId) public pure returns (string memory) {
        if (backId == 4) return "Gingham";
        if (backId == 5) return "Houndstooth";
        if (backId == 6) return "Polka Dots";
        revert("Back ID not in this bank");
    }
}
